frases_clave_preguntas:
- cómo
- cuándo
- qué
- cuál
- dónde
- por qué
- para qué
- qué pasa si
- tengo una consulta
- tengo una duda
- tengo una pregunta
- mi duda es
- mi consulta es
- quisiera consultar
- quería saber si
- me surgió la duda
- necesito saber si
- me pregunto si
- alguien sabe
- una duda
- una consulta
- necesito ayuda
- es posible
- qué debería
- que debería
- duda diferente
- otro problema
